src/modules/survey/creation/components/CreateMoveableSingleSelection.tsx, src/modules/survey/creation/components/CreateQuestion.tsx, src/modules/survey/creation/components/CreateSurveyInfo.tsx, src/modules/survey/creation/components/FloatingActionButtons.tsx, src/modules/survey/creation/constant/SurveyCreationConstant.ts, src/modules/survey/creation/routers/CreateationSurvey.tsx, src/modules/survey/enums/OpenStatusEnum.ts, src/modules/survey/enums/QuestionTypeEnum.ts, src/modules/survey/enums/SurveyStatusEnum.ts, src/modules/survey/preview/components/PreviewSurveyInfo.tsx, src/modules/survey/preview/routers/SurveyPreview.tsx, src/modules/survey/preview/types/PreviewSurveyTypes.tsx
1. 설문조사 작성 validation 코드 리팩토링
2. 설문조사 작성에 사용된 매직 넘버, 상수 => Enum || Constant 클래스로 분리해서 변경
3. 설문조사 작성 중 미리보기 진행중
#1
=> Title: 설문조사 작성 Validation 로직 리팩토링 

src/App.tsx, src/modules/layout/Layout.tsx
<h2>내용</h2>
로그인 라우트 부분 정리가 필요해서 바로 정리해서 병합합니다!
issue: #27
=> [fix] 로그인 페이지 라우트 정리 #27

src/modules/layout/Header.tsx, src/modules/layout/Layout.tsx, src/modules/layout/Menu.tsx
1. 공통 레이아웃 헤더 사이드 바 개발
- 특이사항: @DevPCW 마이페이지 라우트 미작성으로 인해 `navigate` 미작성, @kl204 프론트 인가 사용자 검증 로직 미완성으로 인해 validation 미작성
#33
=> Title: 공통 레이아웃 헤더 사이드 바

.eslintrc.json, src/modules/survey/creation/components/FloatingActionButtons.tsx, src/modules/survey/statistic/components/AnswerList.tsx
=> Title: "작성하기 및 미리보기 일부 css 작업"

src/modules/survey/statistic/components/GooglePieChart.tsx
=> Title: "구글파이차트 에스린트 + yarn run build 문제 해결"

src/modules/layout/Footer.tsx, src/modules/layout/Header.tsx
<h2>내용</h2>
1. Header 타이틀 이름 위치 조정(이미지로 되어있음)<br/>
2. Footer backgroundcolor 적용, position 고정
=> Title: Header & Footer 수정

src/modules/layout/Footer.tsx, src/modules/survey/main/Main.tsx
<h2>내용</h2>
메인 화면 전체보기 버튼 위치 오른쪽으로 조정<br/>
=> Title: 메인 전체보기 위치 조정

src/App.tsx, src/modules/layout/Footer.tsx, src/modules/layout/Menu.tsx, src/modules/layout/MenuTool.tsx, src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/modify/routers/ModifySurvey.tsx, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageUserModify.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx
=> Title: "프론트 라우터 수정 및 각종 하드코딩 3차 수정"

src/modules/survey/creation/components/DragDropQuestions.tsx
1.  Drop&Drop DragEndDetails를 다른 타입으로 교체하여 컴파일 에러를 해결하였습니다.
=> [fix]: Drop&Drop DragEndDetails 다른 타입 교체 컴파일 에러 해결

src/modules/survey/creation/components/CreateSurveyInfo.tsx, src/modules/survey/creation/routers/CreateationSurvey.tsx
1. 설문 작성 성공시 라우터 설정
2. 설문 공개 상태 라벨명 변경
=> Title: 설문 작성시 라우터 설정

src/modules/survey/creation/routers/CreateationSurvey.tsx
1. 설문 작성시 navigate 위치를 메인에서 마이페이지 내가 작성한 설문 페이지로 변경
=> Title: 설문 작성시 navigate 위치 변경

src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx, src/modules/survey/statistic/StatisticsPage.tsx, src/modules/survey/statistic/components/AnswerList.tsx, src/modules/survey/statistic/types/SurveyStatisticTypes.tsx, yarn.lock
**내용**
1. 통계보기 로직 일부 수정
2. 기타 하드코딩 및 코드 수정
Issue: #59
=> Title: "프론트 하드코딩 수정 4차"

.gitignore, src/modules/login/LoginNaver.tsx, src/modules/survey/creation/routers/CreateationSurvey.tsx, src/modules/survey/modify/routers/ModifySurvey.tsx
1. 배포로 인한여 환경 변수 분리 작업을 진행했습니다.
=> Title: 배포 환경 변수 분리 

src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/main/Search.tsx, src/modules/survey/main/components/ClosingSurvey.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/modify/routers/ModifySurvey.tsx, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageUserModify.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx, src/modules/survey/statistic/StatisticsPage.tsx
=> Title: "배포 전 하드코딩 수정 5차 마무리"

src/modules/layout/Menu.tsx, src/modules/login/components/customApi.tsx, src/modules/survey/attend/components/LongAnswer.tsx, src/modules/survey/attend/components/ShortAnswer.tsx, src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/main/Search.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/modify/routers/ModifySurvey.tsx, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageUserModify.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx
**내용**
제목과 동일(커밋 내용 확인 요망)
Issue: #72
=> Title: "각종 라우터 설정 및 코드 리펙토링 7차"

src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/main/Search.tsx, src/modules/survey/main/components/ClosingSurvey.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/modify/routers/ModifySurvey.tsx, src/modules/survey/statistic/StatisticsPage.tsx
=> Title: "메인 상세 모달 수정 1차"

src/modules/survey/creation/components/CreatShortAnswer.tsx, src/modules/survey/creation/components/CreateMoveableSingleSelection.tsx, src/modules/survey/creation/components/CreateMultipleSelection.tsx, src/modules/survey/creation/components/CreateQuestion.tsx, src/modules/survey/creation/components/CreateSingleSelection.tsx, src/modules/survey/creation/components/CreateSubjectiveDescriptive.tsx, src/modules/survey/creation/components/CreateSurveyInfo.tsx, src/modules/survey/creation/components/FloatingActionButtons.tsx, src/modules/survey/creation/routers/CreateationSurvey.tsx, src/modules/survey/statistic/StatisticsPage.tsx
작성 페이지 폰트 메인과 동일하게 변경
통계 페이지 카드 width 조정
#80
=> Title : 작성페이지 폰트 통일 및 통계 카드 너비 조정 

src/App.tsx, src/modules/layout/Header.tsx, src/modules/layout/Layout.tsx
=> Title:  폰트 전역 적용

src/modules/survey/attend/components/AttendSingleMoveChoice.tsx, src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/statistic/StatisticsPage.tsx
**내용**
커밋 메세지 확인 요망
Issue: #81
=> Title: "tetCase 작성 중 일부 기능 작동 안되는 부분들 수정 및 css 업데이트"

src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx
=> Title: "상세 모달 창 수정 2차 진행 중"

src/App.tsx, src/modules/layout/Header.tsx, src/modules/layout/Layout.tsx, src/modules/login/LoginDisplay.tsx, src/modules/survey/main/components/WeeklySurvey.tsx
<h2>내용</h2>
로그인 경로 수정 사항입니다
Issue: #91
=> Title: 로그인 경로 수정 사항

src/App.tsx
폰트 설정 후 경고 내용에 따라 import -> font-face 변경
=> TItle : 폰트 전역 설정 방식 변경

package.json, yarn.lock
1. styled-components devDependency 문젝 해결을 위해 dependency 추가
=> [fix]: styled-components devDependency 문제 해결

public/index.html
1. Https 에서 Http 요청시 block되는 문제를 해결하기 위한 HotFix PR
=> Title:  https 에서 http 통신이 막히는 문제를 위한 Fix

public/index.html
1. 필요없는 meta 태그를 제거 했습니다.
2. 백엔드 서버 https로 변경으로 환경변수를 변경하여서 재배포합니다.
=> Title:  필요없는 meta 태그 제거 & 재배포

src/modules/survey/main/components/Modal.css, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx
=> Title: "모달 상세보기 창 375px에서 반응형 처리 완료"

public/index.html, src/modules/survey/main/components/Modal.css, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx
=> Title: Modal 설정 적용 PR

src/modules/login/LoginDisplay.tsx, src/modules/login/components/NameInput.tsx, src/modules/login/components/customApi.tsx, src/modules/login/config/config.json, src/modules/login/modal/BasicModal.tsx
<h2>내용</h2>
필요 없는 config 내용들 , api 경로 수정
Issue: #106
=> Title: 필요없는 config 제거

src/modules/login/LoginDisplay.tsx
<h2>내용</h2>
redirectUri 경로 수정 사항입니다.
Issue: #114
=> TItle: redirectUri 수정 

src/modules/survey/creation/routers/CreateationSurvey.tsx, src/modules/survey/creation/types/SurveyTypes.tsx, src/modules/survey/creation/util/ValidatorUtil.tsx, src/modules/survey/utils/ImageUploadUtil.tsx
1. S3 이미지 업로드 공통 로직
2. 이미지 업로드 로직 변경으로 인한 코드 변경
#86
=> Title: S3 이미지 업로드 로직 & 변경으로 인한 로직 변경

src/App.tsx, src/modules/layout/Header.tsx, src/modules/survey/main/Main.tsx, src/modules/survey/main/Search.tsx, src/modules/survey/main/components/ClosingSurvey.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx
=> Title : 카드 정렬 변경

src/modules/layout/Layout.tsx, src/modules/survey/attend/components/AttendMultipleChoice.tsx, src/modules/survey/attend/components/AttendSingleChoice.tsx, src/modules/survey/attend/components/AttendSingleMoveChoice.tsx, src/modules/survey/attend/components/LongAnswer.tsx, src/modules/survey/attend/components/ShortAnswer.tsx, src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/mypage/components/MypageUserModify.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx
**내용**
커밋 메세지 확인 바람
Issue: #121
=> Title: "각 컴포넌트 css 수정 및 공동 레이아웃 minWidth설정"

src/modules/layout/Header.tsx, src/modules/login/LoginDisplay.tsx, src/modules/login/components/NameInput.tsx, src/modules/login/components/customApi.tsx, src/modules/login/modal/BasicModal.tsx, src/modules/survey/creation/utils/ImageUploadUtil.tsx
<h2>내용</h2>
로그인 프로필 모달 UI 설정 PR 입니다
Issue : #102
=> Title: 로그인 프로필 모달 UI 설정

src/modules/survey/creation/routers/CreateationSurvey.tsx
1. 설문 게시하기 요청 ContentType 변경했습니다.
- S3 파일 업로드로 인해 mutlipart/form-data -> application/json
#112
=> Title:  설문 게시하기 요청 contentType 변경

src/modules/layout/Footer.tsx
=> Title : footer 디자인 변경 

src/modules/survey/creation/components/CreateQuestion.tsx
1. 설문 작성시 초기 선택지가 생성되지 않던 문제 해결
#133
=> [fix]: 설문 작성시 초기 선택지가 생기지 않던 문제 #133

src/modules/survey/creation/components/CreateSurveyInfo.tsx, src/modules/survey/modify/routers/ModifySurvey.tsx
1. S3 기존 이미지 삭제하기 위해 Custom Header 추가 
#133
=> Title: S3 기존 이미지 삭제하기 위해 Custom Header 추가 

src/modules/survey/mypage/components/MypageAttendSurvey.tsx
=> Title: "참여일 ui 표기 수정"

src/modules/survey/main/components/ClosingSurvey.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx
=> Title: "배포 확인 후 일부 css 및 반응형 수정"

src/modules/login/LoginDisplay.tsx, src/modules/survey/statistic/StatisticsPage.tsx, src/modules/survey/statistic/components/AnswerList.tsx, src/modules/survey/statistic/components/GooglePieChart.tsx, src/modules/survey/statistic/components/WordCloud.tsx
<h2>내용</h2>
통계 보기 UI 수정 및 로그인 isLoading 추가 했습니다<br/>
Issue : #155
=> [anyLeftIssue] 통계 보기 UI 수정 및 로그인 isLoading 추가 

src/modules/survey/main/routes/Main.tsx, src/modules/survey/main/routes/Search.tsx, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx
=> Title: "[fix] header와 Container 간격 조정"

src/modules/login/components/customApi.tsx, src/modules/survey/attend/routers/AttendSurvey.tsx, src/modules/survey/creation/components/CreateSurveyInfo.tsx, src/modules/survey/creation/util/ValidatorUtil.tsx, src/modules/survey/main/components/AttendModalButtonGroup.tsx, src/modules/survey/main/components/ClosingModalButtonGroup.tsx, src/modules/survey/main/components/ClosingSurvey.tsx, src/modules/survey/main/components/MainModal.tsx, src/modules/survey/main/components/RecentSurvey.tsx, src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/main/constant/MainConstant.tsx, src/modules/survey/main/routes/Main.tsx, src/modules/survey/main/types/MainType.tsx
1. 설문 공유하기 기능 추가
2. 메인 페이지 모달 컴포넌트 분리
#158
=> Title: 설문 공유하기 && 메인 페이지 모달 컴포넌트 분리

src/modules/utils/SNSSharing.tsx
=> Title: Hotfix kakao 공유하기 hotfix

public/index.html, src/modules/survey/main/components/MainModal.tsx, src/modules/utils/SNSSharing.tsx, src/modules/utils/SNSSharingType.tsx, src/modules/utils/Sharing.tsx
=> Title: Hotfix Deploy PR

public/index.html, src/modules/survey/main/components/MainModal.tsx, src/modules/utils/SNSSharing.tsx, src/modules/utils/SNSSharingType.tsx, src/modules/utils/Sharing.tsx
=> Title: Hotfix Kakao Share 

src/modules/utils/SNSSharing.tsx
=> Title: 진짜 최종 수정 Kakao Share

src/modules/survey/statistic/StatisticsPage.tsx, src/modules/survey/statistic/components/GooglePieChart.tsx
<h2>내용</h2>
구글 파이차트 색상이 재랜더링시 랜덤으로 교체되는 현상 수정했습니다.<br/>
Issue: #181
=> TItle: 구글 파이차트 색 재랜더링 이슈 해결 

src/modules/layout/Footer.tsx, src/modules/survey/main/routes/Search.tsx
=> Title : footer, modal 디자인 변경

src/modules/survey/statistic/StatisticsPage.tsx, src/modules/survey/statistic/components/GooglePieChart.tsx, yarn.lock
<h2>내용</h2>
통계보기 Font, height 등 수정 사항입니다.<br/>
Issue: #193
=> Title: 통계보기 Font, height 등 수정

src/App.tsx, src/modules/layout/NotFoundPage.tsx, src/modules/survey/creation/components/CreateMoveableSingleSelection.tsx, src/modules/survey/creation/components/CreateSurveyInfo.tsx, src/modules/survey/creation/routers/CreateationSurvey.tsx, src/modules/utils/Sharing.tsx
1. NotFoundPage 를 새롭게 추가 하였습니다.
2. 설문 작성 페이지 배포 핸드폰 화면에서 깨지는 부분을 수정하였습니다.
#112
=> Title: NotFound Page 추가 && 설문 작성 페이지 CSS 수정

src/modules/survey/creation/routers/CreateationSurvey.tsx
=> Title: 설문 작성 회원 인가 기능 수정

src/modules/survey/mypage/components/MypageAttendSurvey.tsx
=> Title: "hotfix => 내가 참여한 설문 페이지 초기화 버튼 및 select 박스 프론트 코드 수정"

src/modules/survey/creation/components/CreateQuestion.tsx, src/modules/survey/creation/components/DragDropQuestions.tsx
1. Fixed Question Required Option During Drag&Drop Reorder
=> Title: Fixed Question Required Option During Drag&Drop Reorder

src/modules/survey/main/components/WeeklySurvey.tsx, src/modules/survey/main/routes/Search.tsx, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageUserModify.tsx, src/modules/survey/mypage/components/MypageWriteSurvey.tsx
=> Title : 모바일 헤더, 컨테이너 간격 조정

src/modules/survey/statistic/StatisticsPage.tsx, src/modules/survey/statistic/components/GooglePieChart.tsx, src/modules/survey/statistic/components/WordCloud.tsx
<h2>내용</h2> 
통계보기 워드 클라우드 수정</br>
Issue: #202
=> Title: 통계보기 워드클라우드 수정 

src/modules/survey/main/components/MainModal.tsx
=> Title: "메인 모달 높이에 따른 반응형 미디어 쿼리 추가"

src/modules/survey/main/routes/Search.tsx
=> Title : 카드 이미지 padding 제거

src/modules/survey/attend/routers/AttendSurvey.tsx
=> Title: "hotfix 필수응답여부 validation scroll 이동 문제 해결"

src/App.tsx, src/modules/layout/Header.tsx, src/modules/survey/main/components/AttendModalButtonGroup.tsx, src/modules/survey/main/components/ClosingModalButtonGroup.tsx, src/modules/survey/main/components/MainModal.tsx, src/modules/survey/main/components/Modal.css, src/modules/survey/mypage/components/MypageAttendSurvey.tsx, src/modules/survey/mypage/components/MypageWriteModal.css, src/modules/survey/mypage/components/MypageWriteSurvey.tsx, src/modules/survey/statistic/StatisticsPage.tsx
=> Title: "프론트 ui 최종 리펙토링"

package.json, src/modules/survey/statistic/components/WordCloud.tsx, yarn.lock
<h2>내용</h2>
워드클라우드 로직 교체, 겹치는 단어 등 올바른 로직으로 교체
<br/>
Issue: #216
=> Title: 워드클라우드 멋진걸로다가 교체

src/modules/login/components/BasicDatePicker.tsx
<h2>내용</h2>
1910년생 이하, 2004년생 이상만 회원가입 가능하도록 하는 Validation
<br/>
Issue: #227
=> Title: 만19세 이상만 사용 가능 회원가입 Validation 
